### ISSUE TITLE
Problema no pré-processamento das previsões

### ISSUE THREAD

**Issue by cfbastarz** [GAM-DIMNT-CPTEC/MEC#4]
Testes da etapa de pré-processamento com o MEC na máquina Itapemirim.

Comando utilizado:
```
./00-MEC.ksh REG21T-test TMIN 00 20220601 20220601 LOWEST MCD
```

**Notas:**

* O script `GS_AccumModelAndRegrid.gs` é criado, mas não há um arquivo para ser aberto (o primeiro arquivo). Esse script é criado a partir do script `GRADS/GS_AccumModelAndRegrid_template.gs`, que é parseado pelos scripts `01.3-PreprocAnlGFS.ksh` (alvo engano, quando a opção `CTL` é usada) e `02-PreprocModels.ksh` (quando a opção `LOWEST` é usada). A linha de comando que substitui as variáveis no script `GRADS/GS_AccumModelAndRegrid_template.gs` é:

```bash
sed -e s:CTL_MODEL::g -e s:CTL_OBS:/oper/share/ioper/tempo/BAM/TQ0666L064/brutos/2022/05/22/00/GPOSNMC2022052200P.fct.TQ0666L064.ctl:g -e s:HS:240:g -e s:DT:2022060100:g -e s:DIR_OUT:.:g -e s:MODELO:BAM_20km_TMIN_240_2022060100:g -e s:VAR:TMIN:g -e 's:ACC_COMMAND:FCT=min(TMIN2m,t=38,t=41)-273.16:g' -e 's:LONGITUDE:277.05 326.95:g' -e 's:LATITUDE:-47.05 12.95:g' -e s:OBS_NEW:SAMeT_TMIN_2022060100:g -e s:dt_obs:2022060112:g -e s:OPEN_COMM:open:g -e s:FCTNEW:VTMIN:g /scripts/ensemble/MEC-DEV/GRADS/GS_AccumModelAndRegrid_template.gs
```

Nesse comando, `s:CTL_MODEL::g` não possui uma substituição e deveria ser o nome do arquivo `ctl` de previsão. A variável a ser substituída (`CTL_MODEL`) é definida, neste exemplo, pelo script `02-PreprocModels.ksh` através das instruções:

```bash
MEC_ctl_model=`echo ${MEC_ctl_full_fname_model}                                | \
                  sed "s:YYYY:${MEC_ini_yea}:g" | sed "s:MM:${MEC_ini_mon}:g"     | \
                  sed "s:DD:${MEC_ini_day}:g"   | sed "s:HH:${VALID_TIME}:g"      | \
                  sed "s:FCT_LT:${MEC_hs_fct2}:g"`
```

A instrução acima utiliza a variável `${MEC_ctl_full_fname_model}` que é definida dentro do script `CONFIG/GFS_30km.ksh` ou `CONFIG/BAM_20km.ksh` (neste ponto, fiz testes com os dois modelos).

O que está faltando para que os arquivos do modelo escolhido (BAM ou GFS) sejam pré-processados corretamente? Esse é um problema relacionado com a opção `MCD` (maximum common domain)?

**Comment by cfbastarz** [comment]
Em conversa com o @Garcia-INPE, foi identificado que na linha de comando `./00-MEC.ksh REG21T-test TMIN 00 20220601 20220601 LOWEST MCD`, o parâmetro correto a ser utilizado é `MERGE_10.ctl` (este é um arquivo que deve constar no diretório `TEMPLATE`). Além disso, como o teste realizado está considerando os arquivos de previsões do modelo BAM, foi necessário também atualizar os nomes das variáveis do modelo no script `CONFIG/BAM_20km.ksh`. Com estas atualizações, foi possível concluir a etapa do pré-processamento do MEC. Estas modificações foram incorporadas no push 4937f93389cf2e6fd5ea215cd998eb041a187178.

**Comment by Garcia-INPE** [comment]
Importante reforçar que a palavra "ctl" deve estar no nome do parâmetro que informa o modo de regrid quando este for baseado em um grib/ctl, como em MERGE_10.ctl.
